name: Go

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-latest]

    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./src/...


  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Build binaries
      run: make build_all

    - name: save binaries
      uses: actions/upload-artifact@v2
      with:
        name: save
        path: bin/**
