name: Go

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04, ubuntu-16.04, ubuntu-18.04]

    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./src/...

    - name: Build binaries
      run: make build

    - name: save binaries
      uses: actions/upload-artifact@v2
      with:
        name: onesky-${{ matrix.os }}
        path: bin/onesky
