name: Go

on:
  push:
    branches:
    - dev-mod

jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      env:
        GOPATH: "/Users/runner/work/onesky-sdk-cli/onesky-sdk-cli"
      run: |
        go version
        go get -v -t -d gopkg.in/yaml.v2
        go get -v -t -d github.com/creack/pty/...
        go get -v -t -d ./...
        
    - name: Build
      env:
        GOPATH: "/Users/runner/work/onesky-sdk-cli/onesky-sdk-cli"
      run: go build -v ./src/onesky.go

    - name: Test
      env:
        GOPATH: "/Users/runner/work/onesky-sdk-cli/onesky-sdk-cli"
      run: go test -v ./src/...
