name: Release

on:
  release:
    types: [created]

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        - os: ubuntu-20.04
          artifact_name: onesky-ubuntu20

        - os: ubuntu-18.04
          artifact_name: onesky-ubuntu18

        - os: ubuntu-16.04
          artifact_name: onesky-ubuntu16

        - os: macos-latest
          artifact_name: onesky-macos

        - os: windows-latest
          artifact_name: onesky-win.exe

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Test
        run: go test -v ./src/...

      - name: Build binaries
        run: make build

      - name: Save binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact_name }}
          path: bin/onesky

      - name: Upload the artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
          overwrite: true

